services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword
    ports:
      - "5050:80" # Access at http://localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: