"""updated relationship for organizations table

Revision ID: 695bd47d4cdc
Revises: 73e2a77ae7e9
Create Date: 2026-05-08 02:32:48.179042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695bd47d4cdc'
down_revision: Union[str, Sequence[str], None] = '73e2a77ae7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
