"""update repositories table

Revision ID: 6ca6dbd97fd0
Revises: 695bd47d4cdc
Create Date: 2026-05-15 01:12:59.971520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca6dbd97fd0'
down_revision: Union[str, Sequence[str], None] = '695bd47d4cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE repositories SET is_private = false")
    
    # Make the column NOT NULL
    op.alter_column('repositories', 'is_private', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_private')
    # ### end Alembic commands ###
