"""add organizations and organization_members table

Revision ID: 73e2a77ae7e9
Revises: 52be477c83fd
Create Date: 2026-05-08 02:22:33.657344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e2a77ae7e9'
down_revision: Union[str, Sequence[str], None] = '52be477c83fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ORGANIZATION', 'USER', name='organizationtype'), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_github_installation_id'), 'organizations', ['github_installation_id'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='organizationmemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.add_column('repositories', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('last_active_org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['last_active_org_id'], ['id'])
    op.drop_column('users', 'installation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('installation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_active_org_id')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'organization_id')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_github_installation_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
