/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleAppRouteImport } from './routes/$locale._app'
import { Route as LocaleAppIndexRouteImport } from './routes/$locale._app.index'
import { Route as LocaleAuthCallbackRouteImport } from './routes/$locale.auth.callback'
import { Route as LocaleAppVulnerabilitiesRouteImport } from './routes/$locale._app.vulnerabilities'
import { Route as LocaleAppSettingsRouteImport } from './routes/$locale._app.settings'
import { Route as LocaleAppRulesRouteImport } from './routes/$locale._app.rules'
import { Route as LocaleAppRepositoriesRouteImport } from './routes/$locale._app.repositories'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppIndexRoute = LocaleAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAuthCallbackRoute = LocaleAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppVulnerabilitiesRoute =
  LocaleAppVulnerabilitiesRouteImport.update({
    id: '/vulnerabilities',
    path: '/vulnerabilities',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSettingsRoute = LocaleAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppRulesRoute = LocaleAppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppRepositoriesRoute = LocaleAppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => LocaleAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAppRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/repositories': typeof LocaleAppRepositoriesRoute
  '/$locale/rules': typeof LocaleAppRulesRoute
  '/$locale/settings': typeof LocaleAppSettingsRoute
  '/$locale/vulnerabilities': typeof LocaleAppVulnerabilitiesRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/': typeof LocaleAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAppIndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/repositories': typeof LocaleAppRepositoriesRoute
  '/$locale/rules': typeof LocaleAppRulesRoute
  '/$locale/settings': typeof LocaleAppSettingsRoute
  '/$locale/vulnerabilities': typeof LocaleAppVulnerabilitiesRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_app': typeof LocaleAppRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/_app/repositories': typeof LocaleAppRepositoriesRoute
  '/$locale/_app/rules': typeof LocaleAppRulesRoute
  '/$locale/_app/settings': typeof LocaleAppSettingsRoute
  '/$locale/_app/vulnerabilities': typeof LocaleAppVulnerabilitiesRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/_app/': typeof LocaleAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/repositories'
    | '/$locale/rules'
    | '/$locale/settings'
    | '/$locale/vulnerabilities'
    | '/$locale/auth/callback'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/repositories'
    | '/$locale/rules'
    | '/$locale/settings'
    | '/$locale/vulnerabilities'
    | '/$locale/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_app'
    | '/$locale/login'
    | '/$locale/_app/repositories'
    | '/$locale/_app/rules'
    | '/$locale/_app/settings'
    | '/$locale/_app/vulnerabilities'
    | '/$locale/auth/callback'
    | '/$locale/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_app': {
      id: '/$locale/_app'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_app/': {
      id: '/$locale/_app/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleAppIndexRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/auth/callback': {
      id: '/$locale/auth/callback'
      path: '/auth/callback'
      fullPath: '/$locale/auth/callback'
      preLoaderRoute: typeof LocaleAuthCallbackRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_app/vulnerabilities': {
      id: '/$locale/_app/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/$locale/vulnerabilities'
      preLoaderRoute: typeof LocaleAppVulnerabilitiesRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/settings': {
      id: '/$locale/_app/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleAppSettingsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/rules': {
      id: '/$locale/_app/rules'
      path: '/rules'
      fullPath: '/$locale/rules'
      preLoaderRoute: typeof LocaleAppRulesRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/repositories': {
      id: '/$locale/_app/repositories'
      path: '/repositories'
      fullPath: '/$locale/repositories'
      preLoaderRoute: typeof LocaleAppRepositoriesRouteImport
      parentRoute: typeof LocaleAppRoute
    }
  }
}

interface LocaleAppRouteChildren {
  LocaleAppRepositoriesRoute: typeof LocaleAppRepositoriesRoute
  LocaleAppRulesRoute: typeof LocaleAppRulesRoute
  LocaleAppSettingsRoute: typeof LocaleAppSettingsRoute
  LocaleAppVulnerabilitiesRoute: typeof LocaleAppVulnerabilitiesRoute
  LocaleAppIndexRoute: typeof LocaleAppIndexRoute
}

const LocaleAppRouteChildren: LocaleAppRouteChildren = {
  LocaleAppRepositoriesRoute: LocaleAppRepositoriesRoute,
  LocaleAppRulesRoute: LocaleAppRulesRoute,
  LocaleAppSettingsRoute: LocaleAppSettingsRoute,
  LocaleAppVulnerabilitiesRoute: LocaleAppVulnerabilitiesRoute,
  LocaleAppIndexRoute: LocaleAppIndexRoute,
}

const LocaleAppRouteWithChildren = LocaleAppRoute._addFileChildren(
  LocaleAppRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAppRoute: typeof LocaleAppRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleAuthCallbackRoute: typeof LocaleAuthCallbackRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAppRoute: LocaleAppRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleAuthCallbackRoute: LocaleAuthCallbackRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
