import type { AnalyticsOverview, Vulnerability } from "@/types/analytics";

export const mockOverview: AnalyticsOverview = {
  summary: {
    total_vulnerabilities: 45,
    total_prs_scanned: 150,
    total_repos_monitored: 12,
    open_vulnerabilities: 10,
  },
  severity_distribution: [
    { severity: "CRITICAL", count: 2 },
    { severity: "HIGH", count: 15 },
    { severity: "MEDIUM", count: 20 },
    { severity: "LOW", count: 8 },
  ],
  status_distribution: [
    { status: "OPEN", count: 10 },
    { status: "IN_PROGRESS", count: 5 },
    { status: "FIXED", count: 25 },
    { status: "IGNORED", count: 5 },
  ],
  top_vulnerable_files: [
    { file_path: "src/auth/login.ts", issue_count: 5 },
    { file_path: "src/api/gateway.ts", issue_count: 4 },
    { file_path: "config/settings.yaml", issue_count: 3 },
  ],
  vulnerabilities_by_repo: [
    { repo_name: "my-secure-app", count: 12 },
    { repo_name: "billing-service", count: 8 },
    { repo_name: "auth-gateway", count: 15 },
  ],
};

export const mockFeed: Vulnerability[] = [
  {
    id: 101,
    file_path: "src/auth/login.ts",
    description: "SQL Injection in Login Form",
    severity: "CRITICAL",
    status: "OPEN",
    created_at: "2026-04-28T10:00:00Z",
  },
  {
    id: 102,
    file_path: "config/secrets.env",
    description: "Hardcoded AWS access key in config",
    severity: "CRITICAL",
    status: "OPEN",
    created_at: "2026-04-27T15:11:00Z",
  },
  {
    id: 103,
    file_path: "package.json",
    description: "Outdated dependency: lodash <4.17.21",
    severity: "HIGH",
    status: "IN_PROGRESS",
    created_at: "2026-04-27T08:42:00Z",
  },
  {
    id: 104,
    file_path: "src/billing/transfer.ts",
    description: "Missing CSRF token on /transfer",
    severity: "HIGH",
    status: "OPEN",
    created_at: "2026-04-26T18:30:00Z",
  },
  {
    id: 105,
    file_path: "src/auth/jwt.ts",
    description: "Weak JWT secret length",
    severity: "MEDIUM",
    status: "OPEN",
    created_at: "2026-04-26T11:05:00Z",
  },
  {
    id: 106,
    file_path: "src/api/error.ts",
    description: "Verbose error responses leak stack",
    severity: "MEDIUM",
    status: "FIXED",
    created_at: "2026-04-25T22:14:00Z",
  },
  {
    id: 107,
    file_path: "src/marketing/redirect.ts",
    description: "Open redirect on /go",
    severity: "LOW",
    status: "FIXED",
    created_at: "2026-04-24T09:00:00Z",
  },
  {
    id: 108,
    file_path: "src/auth/login.ts",
    description: "Missing rate limit on /login",
    severity: "HIGH",
    status: "OPEN",
    created_at: "2026-04-23T07:50:00Z",
  },
  {
    id: 109,
    file_path: "tools/setup.sh",
    description: "Insecure cookie flags",
    severity: "LOW",
    status: "IGNORED",
    created_at: "2026-04-22T16:00:00Z",
  },
  {
    id: 110,
    file_path: "src/media/upload.ts",
    description: "Unrestricted file upload size",
    severity: "MEDIUM",
    status: "OPEN",
    created_at: "2026-04-21T12:00:00Z",
  },
];
